-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-yaml
    -   id: debug-statements
        language_version: python2.7
    -   id: flake8
        language_version: python2.7
    -   id: check-yaml
    -   id: check-json
    -   id: check-merge-conflict
    -   id: name-tests-test
        exclude: tests/helpers/(.+).py
    -   id: fix-encoding-pragma
    -   id: check-added-large-files
    -   id: check-byte-order-marker
-   repo: https://github.com/asottile/reorder_python_imports
    sha: v0.3.0
    hooks:
    -   id: reorder-python-imports
        language_version: python2.7
        args:
        - --add-import
        - from __future__ import absolute_import
        - --add-import
        - from __future__ import unicode_literals
