branches:
  only:
  - master
  - /^v[0-9.]+$/
language: python
python:
  - '2.7'
services:
  - docker
install:
 - echo mysql-apt-config mysql-apt-config/select-server select mysql-5.7 | sudo debconf-set-selections
 - wget http://dev.mysql.com/get/mysql-apt-config_0.7.3-1_all.deb
 - sudo dpkg --install mysql-apt-config_0.7.3-1_all.deb
 - sudo apt-get update -q
 - sudo apt-get install -q -y -o Dpkg::Options::=--force-confnew mysql-server
 - sudo mysql_upgrade
 - pip install coveralls tox
script:
  - make -f Makefile-opensource test
  - make -f Makefile-opensource itest
after_success:
  - coveralls
