rbr_source_cluster: refresh_primary

schema_tracker_cluster: repltracker

rbr_state_cluster: replhandler

register_dry_run: True

publish_dry_run: True

disable_sensu: True

topology_path: /nail/srv/configs/topology.yaml

namespace: dev

disable_meteorite: False

container_name: dev

container_env: raw

schema_blacklist:
    - information_schema
    - mysql
    - performance_schema
    - test
    - yelp_heartbeat

table_whitelist:
    - advertiser
    - business_payment_account_entity
    - payment_account_entity
    - payment_feature
    - payment_program
    - salesperson

module_env_config:
    - namespace: data_pipeline
      config:
        load_schematizer_host_and_port_from_smartstack: False
